package model;

// Generated 18/01/2015 11:29:36 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Momento generated by hbm2java
 */
public class Momento implements java.io.Serializable {

	private Long id;
	private String nome;
	private Set musicas = new HashSet(0);

	public Momento() {
	}

	public Momento(String nome) {
		this.nome = nome;
	}

	public Momento(String nome, Set musicas) {
		this.nome = nome;
		this.musicas = musicas;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set getMusicas() {
		return this.musicas;
	}

	public void setMusicas(Set musicas) {
		this.musicas = musicas;
	}
	
	@Override
	public String toString() {
		return this.getNome();
	}
	
//	@Override
//	public boolean equals(Object obj) {
//		return this.getId() == this.getId();
//	}

}
